services:
  ozone:
    image: ozone:dev
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  mongo:
    image: mongo:8
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ozone
      - MONGO_INITDB_ROOT_PASSWORD=ozone
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
